////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

[#release-notes-2-24-3]
== 2.24.3

Release date:: 2024-12-10

This release fixes two minor bugs.


[#release-notes-2-24-3-fixed]
=== Fixed

* Fix `ConcurrentModificationException`, if multiple threads modify loggers concurrently. This bug affects users that modify logger levels programmatically. (https://github.com/apache/logging-log4j2/issues/3234[3234])
* Protects `PropertiesUtil` against property sources that call `PropertiesUtil` recursively. In some cases such a property source can even cause deadlocks. (https://github.com/apache/logging-log4j2/issues/3252[3252])
